name: Release Draft

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
      types: [published]

permissions:
  contents: write

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:
    - name: Release Draft
      uses: crs-k/release-draft@b232aaf8608c0ba7df6d7c6382fffa238230e9b1 # v0.7.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"